repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.15
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        args: [--ignore-missing-imports, --no-strict-optional]
        additional_dependencies: [types-PyYAML, types-requests]
        files: ^src/

  - repo: local
    hooks:
      - id: tests
        name: pytest
        entry: pytest tests/ -v
        language: system
        pass_filenames: false
        always_run: false
        stages: [pre-push]
